############################################
# Client Configuration 
############################################
[client]
server_addr = "10.0.0.44:8000"

############################################
# Server Configuration 
############################################
[server]
port = 8000

# Camera configuration settings
# These settings are for NEXIGO N60 Webcam with a factor configuration
# https://drive.google.com/file/d/10IgEGNXSWZNjBNJv240IYPmdfYQsQpE6/view
[server.camera]
# HTTP stream URL for MJPEG video feed
# https://github.com/gen2brain/cam2ip
stream_url = "http://10.0.0.44:56000/mjpeg"
# Number of frames per second
frame_rate = 10
# Horizontal field of view angle in degrees
horizontal_fov = 89.0
# Vertical field of view angle in degrees
vertical_fov = 48.0
# Horizontal offset angle in degrees (azimuth adjustment)
azimuth_offset = 0.0
# Vertical offset angle in degrees (elevation adjustment)
elevation_offset = 0.0

# YOLO object detection model configuration
[server.yolo]
# Path to the YOLO model configuration file
model_cfg = "models/yolov4-tiny.cfg"
# Path to the pre-trained YOLO model weights file
model_weights = "models/yolov4-tiny.weights"
# Input image size for the YOLO model (in pixels)
input_size = 416
# Scale factor for normalizing input pixel values (1/255)
scale_factor = 0.00392156862745098
# Minimum confidence threshold for object detection
confidence_threshold = 0.5
# Confidence threshold for non-maximum suppression
nms_confidence_threshold = 0.5
# IoU threshold for non-maximum suppression
nms_threshold = 0.4
# Minimum score threshold for keeping detections
score_threshold = 1.0
# Maximum number of detections to keep (0 = no limit)
top_k = 1
